[Feat] 사진 업로드 및 사용자 프로필 변경 기능
TF3-Project-PhotoSpot/photospot-be pull request #37
Opened 2024-01-17 20:56 UTC by Ojeegu

## ✅ PR 타입

- [x] 기능 추가
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트

<br>

## 🔁 변경/추가 사항

- 사진 엔티티를 Photo -> PostPhoto로 변경했습니다. 프로필(및 다른 사진)과 방명록에 쓰이는 사진을 명시적으로 구분하고자 변경했습니다.
- S3 버킷 설정을 ACL 활성화로 해두었는데 보안상 권장되지 않는 방법이라 다른 방법으로 수정해야 할 것 같습니다.
- 사진 업로드 기능을 추가했습니다.
  - 방명록 사진은 방명록 업로드 API와 별개로 사진 업로드 API 요청을 따로 두었습니다.
  - 방명록 사진은 최초 업로드 시 temp 폴더로 저장되었다가 매일 새벽 4시마다 유효한(post 존재) 사진에 한해서 post_images 폴더로 이동하고, db에 저장된 url도 그에 맞게 변경하도록 스케줄링 했습니다.
  - temp 폴더를 정리하는 스케줄러는 몇 가지 고민사항이 있어서 추후 추가할 예정입니다.
  - 프로필 사진 업로드는 UserService에서 사진 업로드 메서드를 호출하도록 처리했습니다.   

<br>

## 🙏🏻 To Reviewers

- 스케줄러 테스트 코드에서 헤매느라 시간이 좀 오래 걸렸습니다. 개발 환경과 테스트 환경에서 각각 스케줄링 시간을 따로 설정하여 테스트 환경에서는 매 3초마다 스케줄러가 동작하도록 구현하고 싶었는데 잘 안되더라구요🥲 awaitility 써서 하려고 했는데 Transactional 문제 때문인지 계속 안되서 임의로 스케줄러를 호출하여 확인했습니다.
  - 로컬 환경에서는 포스트맨을 이용하여 스케줄러가 정상적으로 동작하는 것을 확인했습니다.
- 추후 jMeter를 이용해 업로드 속도를 측정하여 개선하도록 하겠습니다. 
- 테스트 application.yml 파일을 환경 변수 없이 더미 값으로 넣으니
  ```
test application.yml에서 로컬이랑 동일한 환경변수 안 쓰면 java.lang.IllegalStateException: ApplicationContext failure threshold (1) exceeded: skipping repeated attempt to load context for [WebMergedContextConfiguration@52d57307 testClass 
  ```
위와 같은 에러가 발생하여 우선은 다시 환경변수로 변경했습니다. 시간 될 때 테스트 환경을 맞추는 것이 좋을 것 같아요.

<br>

## Test
![스크린샷 2024-01-18 오전 5 55 49](https://github.com/TF3-Project-PhotoSpot/photospot-be/assets/107015624/3a416e4b-bf3f-43e2-a712-625f0ca34f48)

2024-01-18 07:34 UTC, tjdqls1200 requested changes
스케줄링 부분은 테스트하기 까다로울텐데 고생 많으셨습니다 ㅠㅠ

이미지 API는 이미지만 S3에 저장을 하고 temp/ 경로에 저장된 url을 반환하면 클라이언트에서 프로필, 방명록 등을 저장할때 url과 추가 데이터를 같이 전달하는 식으로 구현하는 것은 어떤가요? 
사진을 S3의 temp/ 경로에 저장을 하는 것은 사진만 업로드가 되고 최종적으로 프로필, 방명록 등의 저장이 되지 않을 경우 temp 디렉토리만 제거를 하기 위해서 하는 것인데Photo가 같이 DB에 저장이 되면 temp 경로를 사용할 이유가 없는 것 같습니다..!
서버에서 스케줄링 돌릴 필요 없이 CloudWatch event로 스케줄링을 하거나 프로필, 방명록 등을 저장할때 temp/ 경로에 있던 것을 moveAndDelete 해주면 스케줄링 없이도 가능할 것 같습니다

2024-01-20 19:43 UTC, Ojeegu commented on src/main/java/com/tf4/photospot/global/util/S3Uploader.java
> +public class S3Uploader {
저도 패키지를 좀 고민했는데 현재 Photo 패키지는 말 그대로 방명록에 올라가는 사진에 대한 도메인이라고 생각해서 S3에 업로드하는 기능은 util에 좀 더 맞지 않나 싶었습니다.

2024-01-20 19:44 UTC, Ojeegu commented on build.gradle
> +    implementation group: 'org.springframework.cloud', name: 'spring-cloud-starter-aws', version: '2.2.6.RELEASE'
3버전을 사용했을 때 오류가 나서 오류가 안나는 버전을 찾다보니 2.2.6 버전이 되었는데 다른 이유 때문에 오류가 났을 수도 있으니 다시 3버전으로 수정해보겠습니다~

2024-01-20 19:46 UTC, Ojeegu commented on src/main/java/com/tf4/photospot/global/util/S3Uploader.java
> +public class S3Uploader {
이미지 temp/ 경로 관련 수정까지 해보고 이 pr에 그대로 올리겠습니다~

2024-01-22 18:15 UTC, Ojeegu commented on src/main/java/com/tf4/photospot/global/util/S3Uploader.java
> +			throw new RuntimeException();
마땅한 예외가 생각나지 않는데 HttpStatus를 500번대로 하는 것보다 400번대로 하는 게 낫나요? 예외가 발생하는 경우가 예상치 못한 클라이언트의 문제 또는 서버 문제 둘 중 하나일 텐데 두 경우 모두 구체적으로 하기엔 광범위해서요.

2024-01-23 04:59 UTC, tjdqls1200 approved these changes
수고 많으셨습니다~

2024-01-23 04:59 UTC, tjdqls1200 commented on src/main/java/com/tf4/photospot/photo/presentation/request/PostPhotoSaveRequest.java
>  // Todo : 중심 좌표 validate 어떻게 할 건지
아래와 같이 사용하시면 RequestResponseBodyMethodProcessor에서 `@Valid`를 체크하고 제가 Custom ConstraintValidator로 등록한 CoordinateValidator로 validation 해줍니다

```java
@PostMapping("/test")
public ApiResponse<?> test(@RequestBody @Valid PostPhotoSaveRequest) {
}
```

```java
public record PostPhotoSaveRequest(
	String photoUrl,
	@KoreaCoordinate
	CoordinateDto coord,
	String takenAt
) {
}
```

2024-01-23 08:33 UTC, Ojeegu commented on src/main/java/com/tf4/photospot/global/util/S3Uploader.java
> +			throw new RuntimeException();
그럼 500번으로 하겠습니다~

2024-01-23 08:36 UTC, Ojeegu commented on build.gradle
> +    implementation group: 'com.amazonaws', name: 'aws-java-sdk-s3', version: '1.12.641'
현재 코드로는 S3Template을 사용하지 않아서 `implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3'` 의존성이 필요 없을것 같습니다.

2024-01-23 08:37 UTC, Ojeegu commented on src/main/java/com/tf4/photospot/photo/presentation/request/PostPhotoSaveRequest.java
>  // Todo : 중심 좌표 validate 어떻게 할 건지
네 감사합니다. 적용하겠습니다~

2024-01-23 09:33 UTC, merged